theme = "onedark"
[keys.normal]


# scooter integration
C-e = [
  ":write-all",
  ":insert-output scooter >/dev/tty",
  ":redraw",
  ":reload-all"
]

# lazygit integration
C-g = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":redraw",
  ":reload-all"
]

[keys.normal.space]
# yazi integration - open at current buffer's directory
e = [
  ":sh rm -f /tmp/unique-file-u41ae14",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-u41ae14",
  ":insert-output echo \"\\x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-u41ae14}",
  ":redraw"
]

# yazi integration - open at workspace directory  
E = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{workspace_directory}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"\\x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw"
]
